title="Bioinformatics and bio-complexity"
location="Utrecht University"
city="Utrecht"
start_date="09-2020"
end_date="07-2021"
skills=["Biological Modeling", "R", "Python3", "Scientific writing"]
description="Completed 18.5 credits towards an M.Sc. Did a major internship in database- and front-end development."
