title="Biology and medical laboratory research"
location="Avans Hogeschool"
city="Breda"
start_date="09-2015"
end_date="08-2019"
skills=["Molecular biology", "PCR", "Medical research", "Bioinformatics", "R", "Scientific writing"]
description="Earned the degree Bachelor of Science (B.Sc.) in Augustus 2019. Did a major and minor bioinformatics internship at Erasmus MC Rotterdam, minor in bioinformatics (GPA 8.5) and a specialisation in biotechnology. Graduated with a grade point average of 7.5."
