name="Luuk Perdaems"
# Note that the image is saved in the static web application folder (src/web_application/static at the moment of writing)
image="profile_picture.png"
github="Github.com/LuukHenk"
linkedin="Linkedin.com/in/luukperdaems/"
