title="Bioinformatician and biomedical researcher"
location="Erasmus MC (B.Sc. intern)"
city="Rotterdam"
start_date="09-2018"
end_date="08-2019"
skills=["R", "Bash", "RNA isolation", "PCR", "Scientific writing", "Git"]
description="""
    Used R to compare genomic data of patients with aberrant splicing events with healty genomic data,
    to gain more insight in SF3B1-associated aberrant splicing events.
    Used biomedical research to validate our results.
"""
